### ISSUE TITLE
Support Auto-Render

### ISSUE THREAD

**Issue by teocomi** [lucpotage/vue-katex#10]
Hi,
is there any plan to support the [auto-render](https://katex.org/docs/autorender.html) extension?
I'm looking for a way to render all the math in some text without having to specify directives or KatexElement components for each expression since the text is retrieved dynamically and these wouldn't work...

**Comment by lucpotage** [comment]
Hello,

After reading the KaTeX docs, extending the current directive makes sense too, especially because auto-rendering will ignore the `displayMode` option. What about something like `<div v-katex:auto />`?

As for the new component name, I’m not sure `<KatexText>` is clear. Why not a simple `<Katex>` component?

**Comment by shadskii** [comment]
#16 adds support for auto-render. I liked the idea of adding the auto argument to `v-katex` because it is more fluent than wrapping all content in a `<KatexText>` component. Check out the PR and let me know what you think!

Cheers,

Jake

**Comment by teocomi** [comment]
@lucpotage sounds good to me!
