### ISSUE TITLE
Can't inject in Laravel Nova field

### ISSUE THREAD

**Issue by 4n70w4** [lucpotage/vue-katex#32]
Hi! I tried to make Laravel Nova field from vue-katex, but don't works(

https://nova.laravel.com/docs/3.0/customization/fields.html

Field file:

```vue
<template>
    <panel-item :field="field">
        <template slot="value">
        <div v-katex="'\\frac{a_i}{1+x}'"></div>
        <div v-katex:display="'\\frac{a_i}{1+x}'"></div>
        <div v-katex="{ expression: '\\frac{a_i}{1+x}', options: { throwOnError: false }}"></div>
        <div v-katex:auto>
            \(\frac{a_i}{1+x}\)
        </div>
        <div v-katex:auto="{ options }">
            \(\frac{a_i}{1+x}\)
        </div>
        <katex-element expression="'\\frac{a_i}{1+x}'"/>
        </template>
    </panel-item>
</template>

<script>
    import Vue from 'vue';
    import VueKatex from 'vue-katex';
    Vue.use(VueKatex);

export default {

    components: {
        VueKatex
    },

    props: ['resource', 'resourceName', 'resourceId', 'field'],
}
</script>


<style>
    @import "../../../node_modules/katex/dist/katex.min.css";
</style>
```

But nothing rendered:

![image](https://user-images.githubusercontent.com/38257723/100992219-fa767100-3564-11eb-9395-66a5fd8f791f.png)

![image](https://user-images.githubusercontent.com/38257723/100992282-0cf0aa80-3565-11eb-80b5-7024911b06cd.png)

No errors in browser console

**Comment by 4n70w4** [comment]
Workaround: copy https://github.com/lucpotage/vue-katex/blob/master/src/components/KatexElement.vue to local repository.

```vue
import KatexElement from './KatexElement'

export default {

    components: {
        KatexElement
    },

...
```


But works only `<katex-element />`. `v-katex` still don't work.

**Comment by shadskii** [comment]
I am not sure the answer to your problem but I have some troubleshooting steps that may help.

I'm not familiar with Larval Nova and I don't know how what extra steps you may need to take in order to install a Vue plugin. It may be the case that vue-katex is not registered in that component due to a nuance with Laravel Nova. 

Double check that katex is installed as a dependency in your project. Vue-katex requires katex as a peer dependency. 

I hope this helps!
